version: '1.0'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: tresenraya
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
###< doctrine/doctrine-bundle ###
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/tresenraya
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/tresenraya
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database