<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TipoFichaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoFichaRepository extends EntityRepository {

}
